### ISSUE TITLE
bhop_lowg [CS:S] broken on custom styles like scroll/lowg etc

### ISSUE THREAD

**Issue by Nairdaa** [hermansimensen/eventqueue-fix#15]
The "jump" height on that map will be just regular jump height rather than the "low grav" intended by that map

**Comment by rtldg** [comment]
not sure this would be caused by eventqueuefix anyway but i don't have this problem with the latest from this repo's master branch

**Comment by Nairdaa** [comment]
Actually, I took the newest release, not the newest branch. I'll test with the newest branch and come back.
That bug was happening with eventqueuefix loaded and gone when it was unloaded btw. But yes, as you said, I'll test the newest branch instead first.

**Comment by Nairdaa** [comment]
I did as I was suggested. Tested with newest bhoptimer version from the masterbranch (3.1.2a) together with newest mater branch of eventqueuefix - still broken.

**Comment by turtlshell** [comment]
Just to elaborate- there are 4 triggers surrounding the startzone on bhop_lowg which lower your gravity when you touch them. With eventqueuefix loaded, upon leaving the startzone these triggers do not activate, and your gravity is 800 as normal- you'd have to strafe back into the triggers to activate them. With eventqueuefix unloaded the map works as intended.

**Comment by Nairdaa** [comment]
Thanks for explaining in details, Tortoise. Nairda can't into explaining stuff.

**Comment by rtldg** [comment]
was because of `shavit_zones_box_offset 0`. added the map to mapfixes https://github.com/shavitush/bhoptimer/commit/7399512f5e98b34d6547008998448d50a303dc08

**Comment by Nairdaa** [comment]
> // Offset zone trigger boxes by this many unit
> // 0 - matches players bounding box
> // 16 - matches players center
> // -
> // Default: "16"
> shavit_zones_box_offset "16"


you sure?

**Comment by rtldg** [comment]
seemed to be the cause for me since i could generally jump and have the gravity set

**Comment by Nairdaa** [comment]
Well. Even tho the reason you mentioned was not the actual reason, the mapfix you posted made it work properly. Thank you!
