### ISSUE TITLE
add a debug cvar or command so you don't have to recompile for the #define

### ISSUE THREAD

**Issue by rtldg** [hermansimensen/eventqueue-fix#16]

**Comment by hermansimensen** [comment]
Most server operators and have no use for this. It would be an extra if statement to run every time an event is queued and served, and I dont think its worth affecting the performance of the plugin for everyone when only a few people need this.

**Comment by rtldg** [comment]
>extra if statement to run

woah crazy performance killer

lame

**Comment by hermansimensen** [comment]
Unnecessary performance impacts are still unnecessary

**Comment by rtldg** [comment]
simple global variable check btw. maybe we should start caching GetTickInterval too since that's a native call

**Comment by rtldg** [comment]
damn it's a shame that one if statement completely blows the frame budget up
