### ISSUE TITLE
[SM 1.11] Exception reported: Pass flags are only supported for virtual hooks.

### ISSUE THREAD

**Issue by Nyano1337** [hermansimensen/eventqueue-fix#19]
https://pastebin.com/wcfSXMdL

Note: i'm using latest sm-1.11 dhooks

**Comment by BoomShotKapow** [comment]
https://github.com/hermansimensen/eventqueue-fix/commit/ce28b301a3d187a96f9c437e81d9d5deefee2fd5

I believe this resolves that issue.

**Comment by ForceBlood** [comment]
I still have this issue with the latest
