### ISSUE TITLE
Odd side effect

### ISSUE THREAD

**Issue by sneak-it** [hermansimensen/eventqueue-fix#9]
Just fired up a new map that has just come out, and noticed a strange side effect of the plugin. The map has teleport trigger entities with these kv's:
```
{
"model" "*79"
"UseLandmarkAngles" "1"
"target" "stage4"
"StartDisabled" "0"
"spawnflags" "1"
"origin" "0 2480 641"
"classname" "trigger_teleport"
"hammerid" "92429"
"OnStartTouch" "!activatorRunScriptCodeself.SetVelocity(Vector(0, 0, self.GetVelocity().z > 0 ? 0 : self.GetVelocity().z));0-1"
}
```
With the plugin enabled, players can telehop. With the plugin disabled, they no longer can. No error logs. Definitely has to do with the OnStartTouch kv, which is supposed to nullify the players speed upon teleport.

Here's the map in question: https://gamebanana.com/mods/307088

**Comment by hermansimensen** [comment]
This should be working properly now.
